import { useAuth } from "@/_core/hooks/useAuth";
import AppFrame from "@/components/AppFrame";
import { PrivacyNote } from "@/components/ConnectionNotice";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { money } from "@/lib/streamwise";
import { trpc } from "@/lib/trpc";
import { Bookmark, CircleUserRound, Compass, ExternalLink, Eye, ShieldCheck, WalletCards } from "lucide-react";
import { Link } from "wouter";

const decisionMeta = { keep: { label: "Keep", color: "bg-[#dcebdd] text-[#296244]", line: "border-[#a4c7a9]" }, pause: { label: "Pause", color: "bg-[#f2e7c6] text-[#785a20]", line: "border-[#ddc77e]" }, cancel: { label: "Cancel candidate", color: "bg-[#f5dfd6] text-[#97482e]", line: "border-[#dfaa96]" } } as const;

export default function Decisions() {
  const { user, loading } = useAuth();
  const decisions = trpc.decisions.get.useQuery(undefined, { enabled: Boolean(user), retry: false });
  return <AppFrame><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:py-14"><div className="max-w-3xl"><p className="eyebrow">Transparent recommendations</p><h1 className="serif mt-2 text-4xl tracking-[-0.045em] text-[#214a3a] sm:text-5xl">A decision, with the workings shown.</h1><p className="mt-3 text-base leading-7 text-[#63756e]">Streamwise categorises each service using exactly four sources: your saved-title availability snapshots, your title horizons, the price/cycle and intent you entered, and the next renewal date you entered. There is no hidden score and no unseen financial data.</p></div>
    <section className="mt-8 grid gap-3 md:grid-cols-4"><InputTile number="01" label="Saved titles" detail="Only your own watchlist" /><InputTile number="02" label="Viewing horizon" detail="Week, month, or later" /><InputTile number="03" label="Plan records" detail="Price, cycle, intent" /><InputTile number="04" label="Renewal timing" detail="Only if you entered it" /></section>
    {!loading && !user ? <SignedOutDecisions /> : decisions.isLoading ? <div className="mt-8 grid gap-4 md:grid-cols-2">{Array.from({ length: 3 }).map((_, index) => <Skeleton key={index} className="h-64 rounded-2xl" />)}</div> : decisions.error ? <div className="mt-8 rounded-2xl border border-[#e0b9a7] bg-[#fbede6] p-5 text-sm text-[#8a4b2c]">We could not calculate decisions right now. Your profile data is unchanged.</div> : decisions.data?.length ? <section className="mt-8 grid gap-4 md:grid-cols-2">{decisions.data.map(item => { const meta = decisionMeta[item.decision]; return <article key={item.subscriptionId} className={`rounded-2xl border bg-[#fcfaf4] p-5 ${meta.line}`}><div className="flex items-start justify-between gap-4"><div><Badge className={`${meta.color} hover:${meta.color}`}>{meta.label}</Badge><h2 className="serif mt-3 text-2xl text-[#234a3a]">{item.title}</h2></div><div className="text-right"><p className="mono text-[0.62rem] uppercase tracking-[0.1em] text-[#75857e]">Equivalent monthly</p><p className="mt-1 text-lg font-semibold text-[#2a5946]">{money(item.monthlyCost, item.currency)}</p></div></div><p className="mt-4 text-sm leading-6 text-[#576d64]">{item.summary}</p><div className="mt-5 rounded-xl bg-[#eff2eb] p-3"><p className="mono text-[0.62rem] uppercase tracking-[0.1em] text-[#6b7e75]">Inputs used</p><p className="mt-1 text-xs leading-5 text-[#536b61]">{item.inputs.matchedTitles} of {item.inputs.plannedTitlesConsidered} saved titles match this service · intent: {item.inputs.userViewingIntent.replace("_", " ")} · {item.daysUntilRenewal === null ? "no renewal date entered" : `${item.daysUntilRenewal} days to renewal`}</p>{item.unlocks.length ? <div className="mt-2 flex flex-wrap gap-1.5">{item.unlocks.map(title => <span key={title.title} className="rounded-full border border-[#d4ded3] bg-white px-2 py-1 text-[0.65rem] text-[#446251]">{title.title} · {title.plannedFor.replace("_", " ")}</span>)}</div> : null}</div><Link href="/wallet" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[#2e644e] underline underline-offset-4">Review wallet entry <ExternalLink className="size-3.5" /></Link></article>; })}</section> : user ? <NoDecisions /> : null}
    <section className="mt-8 rounded-3xl bg-[#e9eee8] p-6 sm:p-8"><div className="flex gap-3"><Eye className="mt-0.5 size-5 shrink-0 text-[#2f674f]" /><div><h2 className="serif text-2xl text-[#315343]">What this cannot tell you.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5e7269]">A matching title may leave a provider, a plan may have changed, and personal preferences do not fit a formula. A “cancel candidate” is a prompt to review the official terms before renewal—not a command or a claim about affordability.</p></div></div></section><div className="mt-6"><PrivacyNote /></div>
  </main></AppFrame>;
}
function InputTile({ number, label, detail }: { number: string; label: string; detail: string }) { return <div className="rounded-2xl border border-[#dad4c7] bg-[#faf8f1] p-4"><p className="mono text-xs text-[#8d6f32]">{number}</p><p className="mt-5 font-semibold text-[#315543]">{label}</p><p className="mt-1 text-xs text-[#6c7e76]">{detail}</p></div>; }
function SignedOutDecisions() { return <div className="mt-8 rounded-3xl border border-dashed border-[#c9c0ae] bg-[#faf8f1]/70 p-9 text-center"><CircleUserRound className="mx-auto size-8 text-[#6b8479]" /><h2 className="serif mt-4 text-2xl text-[#315343]">Sign in to see your inputs.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#65776f]">Recommendations are individual to your saved titles and your subscription records, so there is no generic financial advice here.</p></div>; }
function NoDecisions() { return <div className="mt-8 grid gap-4 md:grid-cols-2"><div className="rounded-3xl border border-dashed border-[#c9c0ae] bg-[#faf8f1]/70 p-7"><WalletCards className="size-7 text-[#6b8479]" /><h2 className="serif mt-4 text-2xl text-[#315343]">First, add a plan.</h2><p className="mt-2 text-sm leading-6 text-[#65776f]">A decision begins with the service, cost, and billing cycle that you choose to enter.</p><Link href="/wallet" className="mt-5 inline-flex items-center gap-1 rounded-full bg-[#1e4a3a] px-4 py-2.5 text-sm font-semibold text-[#fbf8ee]">Open wallet <ExternalLink className="size-3.5" /></Link></div><div className="rounded-3xl border border-dashed border-[#c9c0ae] bg-[#faf8f1]/70 p-7"><Bookmark className="size-7 text-[#6b8479]" /><h2 className="serif mt-4 text-2xl text-[#315343]">Then, save planned viewing.</h2><p className="mt-2 text-sm leading-6 text-[#65776f]">Availability snapshots tie a service only to titles you intend to watch.</p><Link href="/watchlist" className="mt-5 inline-flex items-center gap-1 rounded-full border border-[#bdd0c2] bg-white px-4 py-2.5 text-sm font-semibold text-[#2f624e]">View watchlist <ExternalLink className="size-3.5" /></Link></div></div>; }
