import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import AppFrame from "@/components/AppFrame";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { BellRing, ExternalLink, FileSearch, Loader2, Search, ShieldCheck, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

export default function LeavingSoon() {
  const { user } = useAuth();
  const [region, setRegion] = useState("IN");
  const [researchQuery, setResearchQuery] = useState("");
  const catalog = trpc.catalog.status.useQuery();
  const leads = trpc.community.list.useQuery({ region, kind: "leaving_soon" });
  const research = trpc.ai.research.useMutation();
  return <AppFrame><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:py-14"><section className="max-w-3xl"><p className="eyebrow">Change-aware viewing</p><h1 className="serif mt-2 text-4xl tracking-[-0.045em] text-[#214a3a] sm:text-5xl">Leaving soon, without false certainty.</h1><p className="mt-4 text-base leading-7 text-[#60746a]">Keep confirmed offer changes separate from what people, headlines, and public discussions are noticing. Every lane says what it knows, where it came from, and what it cannot confirm.</p></section>
    <section className="mt-8 grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-[#b9d0bf] bg-[#edf5ee] p-5"><ShieldCheck className="size-5 text-[#2d654d]" /><p className="eyebrow mt-4">Confirmed provider checks</p><h2 className="serif mt-2 text-2xl text-[#214a3a]">Saved-title snapshots</h2><p className="mt-2 text-sm leading-6 text-[#557067]">{catalog.data?.configured ? "Track only saved titles you choose. A changed legal offer can create an opted-in in-app alert." : "The legal catalog is not configured, so Streamwise cannot confirm departures or platform moves yet."}</p><Link href="/watchlist" className="mt-4 inline-flex text-sm font-semibold text-[#275c46] underline underline-offset-4">Manage saved-title tracking</Link></article>
      <article className="rounded-2xl border border-[#e3d1a9] bg-[#fff9ea] p-5"><UsersRound className="size-5 text-[#8b6431]" /><p className="eyebrow mt-4">Community leads</p><h2 className="serif mt-2 text-2xl text-[#5d4828]">Reported, not confirmed</h2><p className="mt-2 text-sm leading-6 text-[#6d5a3b]">Members can name a provider, an optional reported date, a possible destination, and a public source. Moderation and reports protect the feed; nothing here changes legal availability.</p><Link href="/community" className="mt-4 inline-flex text-sm font-semibold text-[#6f4f22] underline underline-offset-4">Add or review a community lead</Link></article>
      <article className="rounded-2xl border border-[#c9d8dc] bg-[#eef4f5] p-5"><FileSearch className="size-5 text-[#356675]" /><p className="eyebrow mt-4">Grounded public-web context</p><h2 className="serif mt-2 text-2xl text-[#294e58]">Inspectable source links</h2><p className="mt-2 text-sm leading-6 text-[#526f77]">AI discovery resolves likely title intent, then surfaces source-linked reporting and public discussion without copying posts or treating claims as a provider fact.</p><Link href="/" className="mt-4 inline-flex text-sm font-semibold text-[#2d6170] underline underline-offset-4">Search grounded public context</Link></article></section>
    <section className="mt-8 rounded-2xl border border-[#d8d0c0] bg-[#fcfaf4] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Community leaving-soon leads</p><h2 className="serif mt-2 text-3xl text-[#214a3a]">What people are flagging in {region}</h2><p className="mt-2 text-sm leading-6 text-[#64766e]">Use these as a reading list, not a countdown. Confirm the offer with the provider or legal catalog before acting.</p></div><div className="grid gap-2"><Label htmlFor="leaving-region">Country</Label><Input id="leaving-region" value={region} maxLength={2} onChange={event => setRegion(event.target.value.toUpperCase())} className="w-24 bg-white" /></div></div>{leads.isLoading ? <p className="mt-5 text-sm text-[#64766e]">Loading public community leads…</p> : leads.error ? <p role="alert" className="mt-5 rounded-xl bg-[#fbe9e2] p-4 text-sm text-[#8a4b2c]">Leaving-soon leads could not be loaded. Try again later.</p> : leads.data?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{leads.data.map(lead => <article key={lead.id} className="rounded-xl border border-[#e1d8c7] bg-white/70 p-4"><div className="flex flex-wrap gap-2"><Badge className="bg-[#fff0d9] text-[#82562c]">Unverified community lead</Badge>{lead.reportedLeavingAt ? <Badge variant="outline">Reported date: {new Date(lead.reportedLeavingAt).toLocaleDateString()}</Badge> : null}</div><h3 className="serif mt-3 text-2xl text-[#274d3e]">{lead.title}</h3><p className="mt-1 text-xs text-[#728077]">{lead.providerName ?? "No provider named"} · {lead.region}</p>{lead.switchesToProviderName ? <p className="mt-2 text-sm text-[#60746a]">Possible next provider: <strong>{lead.switchesToProviderName}</strong></p> : null}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#526b60]">{lead.body}</p>{lead.sourceUrl ? <a href={lead.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#2e634d] underline underline-offset-4">Inspect linked source <ExternalLink className="size-3" /></a> : null}</article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-[#c9c0ae] bg-[#faf8f1] p-6 text-center"><BellRing className="mx-auto size-7 text-[#80673c]" /><h3 className="serif mt-3 text-xl text-[#315343]">No visible community leaving-soon leads yet.</h3><p className="mt-2 text-sm leading-6 text-[#65776f]">{user ? "Share a public, source-linked observation on Community if you have one; it will remain unverified and reportable." : "Sign in to contribute a source-linked community observation."}</p><Link href="/community" className="mt-4 inline-flex text-sm font-semibold text-[#275c46] underline underline-offset-4">Go to Community</Link></div>}</section>
    <section className="mt-8 rounded-2xl border border-[#c9d8dc] bg-[#eef4f5] p-5"><p className="eyebrow">Grounded public-web check</p><h2 className="serif mt-2 text-3xl text-[#294e58]">Look for source-linked reporting, not a rumor score.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#526f77]">Search a title or provider to inspect grounded reporting and public discussion about possible departures or platform changes. The results never create a countdown, confirmed move, alert, or legal offer.</p>{user ? <div className="mt-4 flex flex-col gap-2 sm:flex-row"><div className="flex-1"><Label htmlFor="leaving-research" className="sr-only">Title or provider for grounded leaving-soon research</Label><Input id="leaving-research" value={researchQuery} onChange={event => setResearchQuery(event.target.value)} placeholder="For example: Tenet Netflix leaving soon" className="bg-white" /></div><Button onClick={() => research.mutate({ query: `Leaving-soon or platform-switch public context: ${researchQuery.trim()}`, region, language: navigator.language || "en-US" })} disabled={research.isPending || researchQuery.trim().length < 3} className="bg-[#285f70] text-white hover:bg-[#1f4d5b]">{research.isPending ? <Loader2 className="size-4 animate-spin" /> : <Search className="size-4" />}Inspect sources</Button></div> : <Button onClick={startLogin} className="mt-4 bg-[#285f70] text-white hover:bg-[#1f4d5b]">Sign in to inspect public sources</Button>}{research.isError ? <p role="alert" className="mt-4 rounded-xl bg-[#fbe9e2] p-3 text-sm text-[#8a4b2c]">The public-web check could not be completed. Legal tracking is unaffected.</p> : null}{research.data ? <div className="mt-4 rounded-xl border border-[#cbd8d6] bg-white/80 p-4"><Badge className="bg-[#e1edf0] text-[#356675]">{research.data.status === "lead" ? "Grounded context" : "No grounded source"}</Badge>{research.data.correctionNote ? <p className="mt-3 text-xs text-[#526f77]">{research.data.correctionNote.replace(/\*\*/g, "")}</p> : null}<p className="mt-3 text-sm leading-6 text-[#385966]">{research.data.summary}</p><div className="mt-3 space-y-2">{[...research.data.sources, ...research.data.communitySources].map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="block text-sm font-semibold text-[#2d6170] underline underline-offset-4">{source.kind === "community" ? "Unverified discussion: " : "Reporting / editorial: "}{source.title} <ExternalLink className="inline size-3" /></a>)}</div><p className="mt-3 text-xs leading-5 text-[#687c80]">{research.data.limitation}</p></div> : null}</section>
    <section className="mt-8 rounded-2xl border border-dashed border-[#c3cfcb] bg-[#f3f6f1] p-5"><p className="eyebrow">Provider connection readiness</p><h2 className="serif mt-2 text-2xl text-[#214a3a]">No OTT passwords or private watchlists.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5c7068]">Streamwise does not ask you to sign in to Netflix, Prime Video, or another OTT account inside this app. A future connection is possible only through an official provider-authorized OAuth or API integration with scoped, revocable consent. Until then, use saved-title snapshots and the evidence lanes above.</p></section>
  </main></AppFrame>;
}
