import AppFrame from "@/components/AppFrame";
import { ConnectionNotice, PrivacyNote } from "@/components/ConnectionNotice";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { clientProviderGuides } from "@/lib/providerGuides";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, ExternalLink, HelpCircle, Landmark, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function ProviderPage() {
  const [, params] = useRoute("/providers/:slug");
  const status = trpc.catalog.status.useQuery();
  const provider = clientProviderGuides.find(item => item.slug === params?.slug);
  return <AppFrame><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:py-14"><Link href="/wallet" className="inline-flex items-center gap-1 text-sm font-semibold text-[#2f644e] underline underline-offset-4"><ArrowLeft className="size-3.5" />Back to wallet</Link>{!provider ? <div className="mt-8 rounded-3xl border border-dashed border-[#c9c0ae] bg-[#faf8f1]/70 p-8"><h1 className="serif text-3xl text-[#315343]">Provider guide not found.</h1><p className="mt-2 text-sm leading-6 text-[#65776f]">This manually entered service does not have a Streamwise guide yet. Use its official account page for current plan and cancellation terms.</p></div> : <><div className="mt-8 max-w-3xl"><p className="eyebrow">Provider decision guide</p><h1 className="serif mt-2 text-5xl tracking-[-0.05em] text-[#204a3a]">{provider.name}</h1><p className="mt-4 text-lg leading-8 text-[#5e7269]">{provider.description}</p></div><div className="mt-8 grid gap-4 md:grid-cols-3"><GuideCard icon={<Landmark className="size-5" />} title="Plan context" text="Streamwise does not copy or infer regional plan pricing. Compare your entered plan, billing cycle, and renewal date with the provider’s current account terms." /><GuideCard icon={<CheckCircle2 className="size-5" />} title="Legal alternatives" text="Use title search to compare current subscription, free/ad-supported, rental, and purchase categories for your selected country." /><GuideCard icon={<ShieldCheck className="size-5" />} title="Decision boundary" text="A recommendation reflects only your saved title snapshots and the wallet fields you supplied. It is not financial advice or a claim about plan eligibility." /></div><div className="mt-6 rounded-3xl bg-[#1e4a3a] p-6 text-[#f9f7ee] sm:p-8"><p className="eyebrow text-[#bdd0b5]">Official next step</p><h2 className="serif mt-2 text-3xl">Review the terms where they live.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#d3e1d8]">Provider help and account pages are the authoritative source for cancellations, refunds, pauses, trials, tax, bundles, and territory-specific conditions.</p><div className="mt-5 flex flex-wrap gap-3"><a href={provider.supportUrl} target="_blank" rel="noreferrer"><Button className="bg-[#f0e3c1] text-[#1e4a3a] hover:bg-white">Open official help <HelpCircle className="size-4" /></Button></a>{provider.cancellationUrl && <a href={provider.cancellationUrl} target="_blank" rel="noreferrer"><Button variant="outline" className="border-[#a7c4b6] bg-transparent text-[#f7f6ee] hover:bg-[#315d4b] hover:text-white">Cancellation guidance <ExternalLink className="size-4" /></Button></a>}</div></div><div className="mt-6"><ConnectionNotice configured={status.data?.configured ?? false} /></div></>}<div className="mt-8"><PrivacyNote /></div></main></AppFrame>;
}
function GuideCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-2xl border border-[#d8d0c0] bg-[#fcfaf4] p-5"><span className="text-[#4f7967]">{icon}</span><h2 className="serif mt-4 text-2xl text-[#315343]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#64766e]">{text}</p></article>; }
