import { useAuth } from "@/_core/hooks/useAuth";
import AppFrame from "@/components/AppFrame";
import AiResearchPanel from "@/components/AiResearchPanel";
import CatalogOfferPreview from "@/components/CatalogOfferPreview";
import CardCommunityContribution from "@/components/CardCommunityContribution";
import CommunityRatingSummary from "@/components/CommunityRatingSummary";
import LeavingSoonSignal from "@/components/LeavingSoonSignal";
import QuickWatchlistSave from "@/components/QuickWatchlistSave";
import TitleDialog from "@/components/TitleDialog";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Bot, ExternalLink, Loader2, Send, ShieldCheck, Sparkles, Star, TrendingUp } from "lucide-react";
import { useState } from "react";

export default function Recommendations() {
  const { user } = useAuth();
  const [mode, setMode] = useState<"popular" | "top_rated" | "genre">("popular");
  const [genreId, setGenreId] = useState<number | undefined>();
  const [mediaType, setMediaType] = useState<"movie" | "tv" | "all">("all");
  const [adaptationNoticeOpen, setAdaptationNoticeOpen] = useState(false);
  const [selected, setSelected] = useState<{ id: number; mediaType: "movie" | "tv" } | null>(null);
  const [region] = useState("IN");
  const [language] = useState(() => typeof navigator === "undefined" ? "en-US" : navigator.language || "en-US");
  const recommendation = trpc.catalog.discover.useQuery({ mode, mediaType, region, language, genreId }, { retry: false });
  const postWatch = trpc.viewingSignals.postWatchPicks.useQuery({ language }, { enabled: Boolean(user), retry: false });
  const chooseGenre = (id: number) => { setGenreId(id); setMode("genre"); };

  return <AppFrame><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:py-14">
    <p className="eyebrow">Deterministic discovery</p>
    <h1 className="serif mt-2 text-4xl tracking-[-0.045em] text-[#214a3a] sm:text-5xl">Find the next great watch.</h1>
    <p className="mt-3 max-w-2xl leading-7 text-[#63756e]">These lists use catalog popularity, rating, or genre fields, not public discussion. Open a title to verify where it streams in your country.</p>
    <AiRecommendationSearch region={region} language={language} userSignedIn={Boolean(user)} onSelect={setSelected} />
    <div className="mt-7 flex flex-wrap gap-2"><Button variant={mode === "popular" ? "default" : "outline"} onClick={() => setMode("popular")} className={mode === "popular" ? "bg-[#1e4a3a] text-white" : "border-[#adc4b7] text-[#275842]"}><TrendingUp className="size-4" />Popular now</Button><Button variant={mode === "top_rated" ? "default" : "outline"} onClick={() => setMode("top_rated")} className={mode === "top_rated" ? "bg-[#1e4a3a] text-white" : "border-[#adc4b7] text-[#275842]"}><Star className="size-4" />Top rated</Button>{(["all", "movie", "tv"] as const).map(type => <button key={type} onClick={() => setMediaType(type)} className={`rounded-full px-3 py-2 text-sm font-semibold ${mediaType === type ? "bg-[#e4ecdf] text-[#214c39]" : "text-[#64776d]"}`}>{type === "all" ? "Films + series" : type === "movie" ? "Films" : "Series"}</button>)}</div>
    <div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm text-[#63756e]">Genre:</span>{[[28, "Action"], [35, "Comedy"], [18, "Drama"], [878, "Sci‑Fi"]].map(([id, label]) => <button key={id} onClick={() => chooseGenre(Number(id))} className={`rounded-full border px-3 py-1.5 text-sm font-semibold ${mode === "genre" && genreId === id ? "border-[#1e4a3a] bg-[#e4ecdf] text-[#214c39]" : "border-[#cbd7cd] text-[#597168]"}`}>{label}</button>)}<button type="button" onClick={() => setAdaptationNoticeOpen(value => !value)} aria-expanded={adaptationNoticeOpen} className="rounded-full border border-[#d7c7a5] bg-[#fff9e9] px-3 py-1.5 text-sm font-semibold text-[#76592b]">Adaptations</button></div>
    {adaptationNoticeOpen ? <aside className="mt-4 rounded-2xl border border-[#dfd0b1] bg-[#fff9ed] p-4 text-sm leading-6 text-[#705c37]"><strong>Adaptation lists are not guessed.</strong> The current verified catalog fields do not provide a complete, licensed “based on book / source material” relationship. Streamwise will add this route only when a permitted structured source is configured; title, genre, similar, popular, top-rated, and post-watch paths remain catalog-derived.</aside> : null}
    {user ? <section className="mt-8 rounded-3xl border border-[#c3d6c5] bg-[#edf5ee] p-6"><p className="eyebrow">Private post-watch picks</p><h2 className="serif mt-2 text-3xl text-[#214a3a]">Only from titles you recorded.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#597168]">These signals stay private and are never inferred from activity or public discussion.</p>{postWatch.isLoading ? <p className="mt-4 text-sm text-[#597168]">Loading your optional member-recorded viewing signals…</p> : postWatch.error ? <div role="alert" className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e0b9a7] bg-[#fff8f3] p-4 text-sm text-[#8a4b2c]"><span>Private post-watch picks could not be loaded. Your records have not changed.</span><Button size="sm" variant="outline" onClick={() => postWatch.refetch()} className="border-[#bd8c79] text-[#8a4b2c]">Try again</Button></div> : postWatch.data?.titles.length ? <><p className="mt-4 text-sm leading-6 text-[#597168]">{postWatch.data.explanation}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{postWatch.data.titles.map(title => <article key={`${title.mediaType}-${title.id}`} className="rounded-2xl border border-[#bad0c0] bg-white p-4 transition hover:bg-[#f7fbf7]"><button type="button" onClick={() => setSelected({ id: title.id, mediaType: title.mediaType })} className="w-full text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#5d786b]">Catalog pick</p><h3 className="serif mt-2 text-xl text-[#244e3c]">{title.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#65776f]">{title.overview || "Open this title to check verified local offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /></button><LeavingSoonSignal titleId={title.id} mediaType={title.mediaType} /><CardCommunityContribution titleId={title.id} mediaType={title.mediaType} title={title.title} region={region} /></article>)}</div></> : <p className="mt-4 rounded-xl bg-white/65 p-4 text-sm leading-6 text-[#597168]">{postWatch.data?.explanation ?? "No private post-watch picks are available yet. Record a title as watched if you want to opt in."}</p>}</section> : <p className="mt-6 text-sm leading-6 text-[#65776f]">Sign in to optionally record titles you watched and receive private post-watch picks. Streamwise does not infer viewing history.</p>}
    {recommendation.isLoading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <Skeleton key={index} className="h-56 rounded-2xl" />)}</div> : !recommendation.data?.configured ? <div className="mt-8 rounded-3xl border border-[#d9cfb7] bg-[#fffaf0] p-7"><p className="serif text-2xl text-[#315343]">Recommendations are safely on standby.</p><p className="mt-2 text-sm leading-6 text-[#61756c]">{recommendation.data?.explanation ?? "Connect the server-side catalog token to view deterministic lists."}</p></div> : <><p className="mt-6 text-sm text-[#62746d]">{recommendation.data.explanation}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recommendation.data.titles.map(title => <article key={`${title.mediaType}-${title.id}`} className="rounded-2xl border border-[#d9d1c0] bg-[#fcfaf4] p-5 transition hover:border-[#9db9aa]"><button type="button" onClick={() => setSelected({ id: title.id, mediaType: title.mediaType })} className="w-full text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-[#5d786b]">{title.mediaType === "movie" ? "Film" : "Series"}{title.releaseDate ? ` · ${title.releaseDate.slice(0, 4)}` : ""}</span><h2 className="serif mt-3 text-2xl text-[#244e3c]">{title.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#65776f]">{title.overview || "Open this title to check verified local offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /><CommunityRatingSummary titleId={title.id} mediaType={title.mediaType} /><span className="mt-4 inline-block text-sm font-bold text-[#2f634f]">Where to stream →</span></button><LeavingSoonSignal titleId={title.id} mediaType={title.mediaType} /><CardCommunityContribution titleId={title.id} mediaType={title.mediaType} title={title.title} region={region} /></article>)}</div></>}
    <TitleDialog titleId={selected?.id ?? null} mediaType={selected?.mediaType ?? null} region={region} language={language} open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }} />
  </main></AppFrame>;
}

function AiRecommendationSearch({ region, language, userSignedIn, onSelect }: { region: string; language: string; userSignedIn: boolean; onSelect: (title: { id: number; mediaType: "movie" | "tv" }) => void }) {
  const [prompt, setPrompt] = useState("");
  const [lastPrompt, setLastPrompt] = useState("");
  const [preferredOriginalLanguage, setPreferredOriginalLanguage] = useState<string | null>(null);
  const [maxRuntimeMinutes, setMaxRuntimeMinutes] = useState<number | null>(null);
  const [history, setHistory] = useState<Array<{ role: "user" | "assistant"; content: string }>>([]);
  const profile = trpc.tasteProfile.get.useQuery(undefined, { enabled: userSignedIn, retry: false });
  const saveProfile = trpc.tasteProfile.save.useMutation({ onSuccess: () => profile.refetch() });
  const recommendation = trpc.ai.recommend.useMutation({
    onSuccess: data => setHistory(previous => [...previous, { role: "assistant", content: data.conversation?.reply ?? `${data.interpretation.explanation} ${data.explanation}` }]),
    onError: error => setHistory(previous => [...previous, { role: "assistant", content: error.message }]),
  });
  const send = (value = prompt) => {
    const message = value.trim();
    if (message.length < 3 || recommendation.isPending) return;
    setHistory(previous => [...previous, { role: "user", content: message }]);
    setLastPrompt(message);
    setPrompt("");
    recommendation.mutate({ prompt: message, conversationContext: history.slice(-4).map(({ role, content }) => ({ role, content })), region, language, preferredOriginalLanguage, maxRuntimeMinutes });
  };
  const useSavedProfile = () => {
    const saved = profile.data;
    if (!saved) return;
    try { const languages = JSON.parse(saved.preferredLanguagesJson); setPreferredOriginalLanguage(Array.isArray(languages) && typeof languages[0] === "string" ? languages[0] : null); } catch { setPreferredOriginalLanguage(null); }
    setMaxRuntimeMinutes(saved.maxRuntimeMinutes ?? null);
  };
  const saveCurrentProfile = () => saveProfile.mutate({ favoriteGenreIds: recommendation.data?.interpretation.genreId ? [recommendation.data.interpretation.genreId] : [], preferredLanguages: preferredOriginalLanguage ? [preferredOriginalLanguage] : [], maxRuntimeMinutes, includeMovies: true, includeSeries: true });
  const suggestions = ["I want a tense science-fiction film like Inception", "Recommend warm Hindi-language family movies", "I liked a clever crime show — what should I watch next?"];
  return <section aria-labelledby="ai-recommendation-title" className="mt-8 rounded-3xl border border-[#b8d0c0] bg-[#eaf3eb] p-5 shadow-[0_10px_28px_rgba(48,86,65,.06)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow flex items-center gap-2"><Sparkles className="size-4" />AI recommendation chat</p><h2 id="ai-recommendation-title" className="serif mt-1 text-3xl text-[#214a3a]">Tell me what you feel like watching.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5a7267]">Describe a genre, language, mood, or a movie or show you liked. Streamwise interprets the request, then retrieves suggestions from the catalog.</p></div><span className="rounded-full border border-[#bfd2c3] bg-white/70 px-3 py-1.5 text-xs font-semibold text-[#426755]">Catalog-backed picks</span></div>
    {history.length ? <div aria-live="polite" className="mt-5 space-y-3">{history.map((message, index) => <div key={`${message.role}-${index}`} className={`flex gap-2 ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-2xl rounded-2xl px-4 py-3 text-sm leading-6 ${message.role === "user" ? "bg-[#245944] text-white" : "border border-[#cadbce] bg-white text-[#456457]"}`}>{message.role === "assistant" ? <Bot className="mr-2 inline size-4" /> : null}{message.content}</div></div>)}</div> : <div className="mt-5 flex flex-wrap gap-2">{suggestions.map(suggestion => <button key={suggestion} type="button" onClick={() => send(suggestion)} className="rounded-full border border-[#c3d7c7] bg-white/80 px-3 py-2 text-left text-sm font-medium text-[#315b47] transition hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{suggestion}</button>)}</div>}
    <div className="mt-5 flex flex-wrap items-end gap-3 rounded-2xl border border-[#c8d9cb] bg-white/65 p-3"><label className="text-sm font-semibold text-[#416653]">Original language<select aria-label="Recommendation language filter" value={preferredOriginalLanguage ?? ""} onChange={event => setPreferredOriginalLanguage(event.target.value || null)} className="ml-2 rounded-lg border border-[#bbcfbf] bg-white px-2 py-1.5 text-sm"><option value="">Any</option><option value="en">English</option><option value="hi">Hindi</option><option value="ko">Korean</option><option value="ja">Japanese</option><option value="es">Spanish</option></select></label><label className="text-sm font-semibold text-[#416653]">Max film runtime<select aria-label="Recommendation runtime filter" value={maxRuntimeMinutes ?? ""} onChange={event => setMaxRuntimeMinutes(event.target.value ? Number(event.target.value) : null)} className="ml-2 rounded-lg border border-[#bbcfbf] bg-white px-2 py-1.5 text-sm"><option value="">Any</option><option value="90">90 min</option><option value="120">120 min</option><option value="150">150 min</option><option value="180">180 min</option></select></label>{userSignedIn ? <><Button type="button" size="sm" variant="outline" onClick={useSavedProfile} disabled={!profile.data} className="border-[#aac5af] text-[#315c49]">Use saved taste profile</Button><Button type="button" size="sm" variant="outline" onClick={saveCurrentProfile} disabled={saveProfile.isPending} className="border-[#aac5af] text-[#315c49]">Save these preferences</Button></> : <span className="text-xs leading-5 text-[#698076]">Sign in to save filters as a taste profile.</span>}</div>
    <form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={event => { event.preventDefault(); send(); }}><label className="sr-only" htmlFor="ai-recommendation-prompt">Ask for a recommendation</label><textarea id="ai-recommendation-prompt" value={prompt} onChange={event => setPrompt(event.target.value)} rows={2} maxLength={500} placeholder="For example: I want a funny Korean movie like…" className="min-h-12 flex-1 resize-none rounded-2xl border border-[#b8cfbf] bg-white px-4 py-3 text-sm text-[#274e3d] placeholder:text-[#7b8e85] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" /><Button type="submit" disabled={prompt.trim().length < 3 || recommendation.isPending} className="h-auto rounded-2xl bg-[#1e4a3a] px-5 text-white hover:bg-[#153a2d]">{recommendation.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Get recommendations</Button></form>
    {recommendation.data?.configured ? <div className="mt-5"><p className="text-sm leading-6 text-[#527064]">{recommendation.data.explanation}</p>{recommendation.data.titles.length ? <><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{recommendation.data.titles.map(title => <div key={`${title.mediaType}-${title.id}`} className="rounded-2xl border border-[#c7d8c9] bg-white p-4"><button type="button" onClick={() => onSelect({ id: title.id, mediaType: title.mediaType })} className="w-full text-left transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#608171]">{title.mediaType === "movie" ? "Film" : "Series"}{title.releaseDate ? ` · ${title.releaseDate.slice(0, 4)}` : ""}</p><h3 className="serif mt-2 text-xl text-[#244e3c]">{title.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#64786e]">{title.overview || "Open to view country-specific legal offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /></button><LeavingSoonSignal titleId={title.id} mediaType={title.mediaType} /><div className="flex flex-wrap gap-2"><QuickWatchlistSave titleId={title.id} mediaType={title.mediaType} title={title.title} posterPath={title.posterPath} releaseDate={title.releaseDate} region={region} language={language} /><CardCommunityContribution titleId={title.id} mediaType={title.mediaType} title={title.title} region={region} /></div></div>)}</div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-[#416653]">More like this:</span>{recommendation.data.titles.slice(0, 4).map(title => <button key={`follow-${title.id}`} type="button" onClick={() => send(`More like ${title.title}. ${lastPrompt}`)} className="rounded-full border border-[#b6cfba] bg-white px-3 py-1.5 text-sm font-semibold text-[#315c49]">{title.title}</button>)}</div></> : <p className="mt-4 rounded-xl bg-white/70 p-4 text-sm text-[#5a7267]">No catalog matches were returned. Try a broader genre, language, or title reference.</p>}</div> : recommendation.data ? <p className="mt-5 rounded-xl border border-[#dccdab] bg-[#fffaf0] p-4 text-sm leading-6 text-[#6b5b38]">{recommendation.data.explanation}</p> : null}
    {lastPrompt ? <RecommendationConversationResearch research={recommendation.data?.conversation?.research ?? null} userSignedIn={userSignedIn} /> : null}
  </section>;
}

function RecommendationConversationResearch({ research, userSignedIn }: { research: any | null; userSignedIn: boolean }) {
  if (!userSignedIn) return <p className="mt-5 rounded-xl border border-[#d8cfb8] bg-[#fffaf0] p-4 text-sm leading-6 text-[#695b3e]">Sign in to add optional source-linked public-web context to this request. It can include public criticism, movie-blog commentary, and clearly labelled discussion.</p>;
  if (!research) return null;
  return <aside className="mt-5 rounded-2xl border border-[#cbd8cc] bg-[#f2f6f0] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#315c49]"><ShieldCheck className="size-4" />Public reading for this conversation</div><p className="mt-2 text-sm leading-6 text-[#466459]">{research.directResponse}</p>{research.sources?.length ? <div className="mt-3 border-t border-[#d8e2d8] pt-3"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#597366]">Critic and reporting links</p><div className="mt-2 flex flex-wrap gap-2">{research.sources.map((source: any) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border border-[#bfd0c2] bg-white px-3 py-1.5 text-xs font-semibold text-[#2d664e] underline underline-offset-4">{source.title} <ExternalLink className="size-3" /></a>)}</div></div> : null}{research.communitySources?.length ? <div className="mt-3 rounded-xl border border-dashed border-[#decfae] bg-[#fffaf0] p-3"><p className="text-xs font-bold text-[#786033]">Public discussion — unverified</p><p className="mt-1 text-xs leading-5 text-[#796c50]">These links provide reading context only; they do not rank titles or prove legal availability.</p><div className="mt-2 flex flex-wrap gap-2">{research.communitySources.map((source: any) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-[#8b6431] underline underline-offset-4">{source.title} <ExternalLink className="size-3" /></a>)}</div></div> : null}<p className="mt-3 text-xs leading-5 text-[#6d5d37]">{research.limitation}</p></aside>;
}
