import { useAuth } from "@/_core/hooks/useAuth";
import AppFrame from "@/components/AppFrame";
import CatalogOfferPreview from "@/components/CatalogOfferPreview";
import TitleDialog from "@/components/TitleDialog";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Star, TrendingUp } from "lucide-react";
import { useState } from "react";

export default function Recommendations() {
  const { user } = useAuth();
  const [mode, setMode] = useState<"popular" | "top_rated" | "genre">("popular");
  const [genreId, setGenreId] = useState<number | undefined>();
  const [mediaType, setMediaType] = useState<"movie" | "tv" | "all">("all");
  const [adaptationNoticeOpen, setAdaptationNoticeOpen] = useState(false);
  const [selected, setSelected] = useState<{ id: number; mediaType: "movie" | "tv" } | null>(null);
  const [region] = useState("IN");
  const [language] = useState(() => typeof navigator === "undefined" ? "en-US" : navigator.language || "en-US");
  const recommendation = trpc.catalog.discover.useQuery({ mode, mediaType, region, language, genreId }, { retry: false });
  const postWatch = trpc.viewingSignals.postWatchPicks.useQuery({ language }, { enabled: Boolean(user), retry: false });
  const chooseGenre = (id: number) => { setGenreId(id); setMode("genre"); };

  return <AppFrame><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:py-14">
    <p className="eyebrow">Deterministic discovery</p>
    <h1 className="serif mt-2 text-4xl tracking-[-0.045em] text-[#214a3a] sm:text-5xl">Find the next great watch.</h1>
    <p className="mt-3 max-w-2xl leading-7 text-[#63756e]">These lists use catalog popularity, rating, or genre fields, not public discussion. Open a title to verify where it streams in your country.</p>
    <div className="mt-7 flex flex-wrap gap-2"><Button variant={mode === "popular" ? "default" : "outline"} onClick={() => setMode("popular")} className={mode === "popular" ? "bg-[#1e4a3a] text-white" : "border-[#adc4b7] text-[#275842]"}><TrendingUp className="size-4" />Popular now</Button><Button variant={mode === "top_rated" ? "default" : "outline"} onClick={() => setMode("top_rated")} className={mode === "top_rated" ? "bg-[#1e4a3a] text-white" : "border-[#adc4b7] text-[#275842]"}><Star className="size-4" />Top rated</Button>{(["all", "movie", "tv"] as const).map(type => <button key={type} onClick={() => setMediaType(type)} className={`rounded-full px-3 py-2 text-sm font-semibold ${mediaType === type ? "bg-[#e4ecdf] text-[#214c39]" : "text-[#64776d]"}`}>{type === "all" ? "Films + series" : type === "movie" ? "Films" : "Series"}</button>)}</div>
    <div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm text-[#63756e]">Genre:</span>{[[28, "Action"], [35, "Comedy"], [18, "Drama"], [878, "Sci‑Fi"]].map(([id, label]) => <button key={id} onClick={() => chooseGenre(Number(id))} className={`rounded-full border px-3 py-1.5 text-sm font-semibold ${mode === "genre" && genreId === id ? "border-[#1e4a3a] bg-[#e4ecdf] text-[#214c39]" : "border-[#cbd7cd] text-[#597168]"}`}>{label}</button>)}<button type="button" onClick={() => setAdaptationNoticeOpen(value => !value)} aria-expanded={adaptationNoticeOpen} className="rounded-full border border-[#d7c7a5] bg-[#fff9e9] px-3 py-1.5 text-sm font-semibold text-[#76592b]">Adaptations</button></div>
    {adaptationNoticeOpen ? <aside className="mt-4 rounded-2xl border border-[#dfd0b1] bg-[#fff9ed] p-4 text-sm leading-6 text-[#705c37]"><strong>Adaptation lists are not guessed.</strong> The current verified catalog fields do not provide a complete, licensed “based on book / source material” relationship. Streamwise will add this route only when a permitted structured source is configured; title, genre, similar, popular, top-rated, and post-watch paths remain catalog-derived.</aside> : null}
    {user ? <section className="mt-8 rounded-3xl border border-[#c3d6c5] bg-[#edf5ee] p-6"><p className="eyebrow">Private post-watch picks</p><h2 className="serif mt-2 text-3xl text-[#214a3a]">Only from titles you recorded.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#597168]">These signals stay private and are never inferred from activity or public discussion.</p>{postWatch.isLoading ? <p className="mt-4 text-sm text-[#597168]">Loading your optional member-recorded viewing signals…</p> : postWatch.error ? <div role="alert" className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e0b9a7] bg-[#fff8f3] p-4 text-sm text-[#8a4b2c]"><span>Private post-watch picks could not be loaded. Your records have not changed.</span><Button size="sm" variant="outline" onClick={() => postWatch.refetch()} className="border-[#bd8c79] text-[#8a4b2c]">Try again</Button></div> : postWatch.data?.titles.length ? <><p className="mt-4 text-sm leading-6 text-[#597168]">{postWatch.data.explanation}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{postWatch.data.titles.map(title => <button key={`${title.mediaType}-${title.id}`} onClick={() => setSelected({ id: title.id, mediaType: title.mediaType })} className="rounded-2xl border border-[#bad0c0] bg-white p-4 text-left transition hover:bg-[#f7fbf7] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#5d786b]">Catalog pick</p><h3 className="serif mt-2 text-xl text-[#244e3c]">{title.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#65776f]">{title.overview || "Open this title to check verified local offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /></button>)}</div></> : <p className="mt-4 rounded-xl bg-white/65 p-4 text-sm leading-6 text-[#597168]">{postWatch.data?.explanation ?? "No private post-watch picks are available yet. Record a title as watched if you want to opt in."}</p>}</section> : <p className="mt-6 text-sm leading-6 text-[#65776f]">Sign in to optionally record titles you watched and receive private post-watch picks. Streamwise does not infer viewing history.</p>}
    {recommendation.isLoading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <Skeleton key={index} className="h-56 rounded-2xl" />)}</div> : !recommendation.data?.configured ? <div className="mt-8 rounded-3xl border border-[#d9cfb7] bg-[#fffaf0] p-7"><p className="serif text-2xl text-[#315343]">Recommendations are safely on standby.</p><p className="mt-2 text-sm leading-6 text-[#61756c]">{recommendation.data?.explanation ?? "Connect the server-side catalog token to view deterministic lists."}</p></div> : <><p className="mt-6 text-sm text-[#62746d]">{recommendation.data.explanation}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recommendation.data.titles.map(title => <button key={`${title.mediaType}-${title.id}`} onClick={() => setSelected({ id: title.id, mediaType: title.mediaType })} className="rounded-2xl border border-[#d9d1c0] bg-[#fcfaf4] p-5 text-left transition hover:border-[#9db9aa] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-[#5d786b]">{title.mediaType === "movie" ? "Film" : "Series"}{title.releaseDate ? ` · ${title.releaseDate.slice(0, 4)}` : ""}</span><h2 className="serif mt-3 text-2xl text-[#244e3c]">{title.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#65776f]">{title.overview || "Open this title to check verified local offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /><span className="mt-4 inline-block text-sm font-bold text-[#2f634f]">Where to stream →</span></button>)}</div></>}
    <TitleDialog titleId={selected?.id ?? null} mediaType={selected?.mediaType ?? null} region={region} language={language} open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }} />
  </main></AppFrame>;
}
