import AppFrame from "@/components/AppFrame";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Settings2, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Settings() {
  const { user, loading } = useAuth();
  const profile = trpc.tasteProfile.get.useQuery(undefined, { enabled: Boolean(user), retry: false });
  const [languages, setLanguages] = useState("hi");
  const [runtime, setRuntime] = useState("120");
  const save = trpc.tasteProfile.save.useMutation({ onSuccess: () => { profile.refetch(); toast.success("Taste profile saved."); }, onError: error => toast.error(error.message) });
  const submit = () => save.mutate({ favoriteGenreIds: [], preferredLanguages: languages.split(",").map(value => value.trim().toLowerCase()).filter(value => /^[a-z]{2}$/.test(value)), maxRuntimeMinutes: runtime ? Number(runtime) : null, includeMovies: true, includeSeries: true });
  return <AppFrame><main className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:py-14"><p className="eyebrow">Your settings</p><h1 className="serif mt-2 text-4xl tracking-[-0.045em] text-[#214a3a] sm:text-5xl">Shape the experience you choose.</h1><p className="mt-3 max-w-2xl leading-7 text-[#63756e]">Control saved recommendation preferences and review the account-scoped settings Streamwise uses. Nothing here is inferred from browsing, community activity, or outside accounts.</p>{!loading && !user ? <section className="mt-8 rounded-3xl border border-dashed border-[#c9c0ae] bg-[#faf8f1] p-8 text-center"><Settings2 className="mx-auto size-8 text-[#53776a]" /><h2 className="serif mt-3 text-2xl text-[#315343]">Sign in to manage settings.</h2><p className="mt-2 text-sm text-[#64766e]">Saved preferences belong only to your Streamwise account.</p></section> : <section className="mt-8 rounded-3xl border border-[#c7d9ca] bg-[#edf5ee] p-6"><div className="flex items-center gap-2"><SlidersHorizontal className="size-5 text-[#2e624b]" /><h2 className="serif text-3xl text-[#214a3a]">Optional taste profile</h2></div><p className="mt-2 text-sm leading-6 text-[#567167]">Use this profile as a starting point for AI recommendation filters. You can still change filters for any individual request.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#315b47]">Preferred original-language codes<input aria-label="Preferred language codes" value={languages} onChange={event => setLanguages(event.target.value)} placeholder="hi, ko, ja" className="mt-2 w-full rounded-xl border border-[#b9cfbd] bg-white px-3 py-2.5 font-normal text-[#294f3e]" /></label><label className="text-sm font-semibold text-[#315b47]">Maximum film runtime (minutes)<input aria-label="Maximum film runtime" value={runtime} onChange={event => setRuntime(event.target.value.replace(/\D/g, "").slice(0, 3))} placeholder="120" inputMode="numeric" className="mt-2 w-full rounded-xl border border-[#b9cfbd] bg-white px-3 py-2.5 font-normal text-[#294f3e]" /></label></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={submit} disabled={save.isPending} className="bg-[#1e4a3a] text-white hover:bg-[#153a2d]">Save taste profile</Button>{profile.data ? <span className="text-sm text-[#557269]">Saved profile available for recommendation chat.</span> : null}</div><p className="mt-5 rounded-xl bg-white/70 p-3 text-xs leading-5 text-[#60766d]">Alert controls remain in <a href="/updates" className="font-semibold text-[#2e624b] underline">Updates</a>; wallet and watchlist actions are always confirmed in their own tools.</p></section>}</main></AppFrame>;
}
