import React from "react";
import AnimeAvailabilityPreview from "@/components/AnimeAvailabilityPreview";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BookOpenText, ExternalLink, Sparkles } from "lucide-react";

export default function AnimeDiscoveryPanel({ query, region, language }: { query: string; region: string; language: string }) {
  const anime = trpc.anime.search.useQuery({ query }, { enabled: query.length >= 2, retry: false, staleTime: 10 * 60_000 });
  if (!query) return null;
  return <section className="mt-7 border-t border-[#d9d1c0] pt-7" aria-label="Anime catalogue discovery">
    <div className="mb-4 flex items-end justify-between gap-4"><div><p className="eyebrow">Anime catalogue · AniList</p><h2 className="serif mt-1 text-3xl text-[#244b3b]">Anime discovery, kept separate.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#61756c]">AniList supplies anime metadata. Country-specific offers appear only after an exact legal-catalog match from Streamwise’s offer sources.</p></div><BookOpenText className="mb-1 size-6 shrink-0 text-[#816334]" /></div>
    {anime.isLoading ? <div className="grid gap-4 sm:grid-cols-2">{Array.from({ length: 2 }).map((_, index) => <Skeleton key={index} className="h-72 rounded-2xl" />)}</div> : anime.error || anime.data?.status === "unavailable" ? <div role="alert" className="rounded-2xl border border-[#e5c8b3] bg-[#fff5ec] p-5 text-sm leading-6 text-[#855435]">The AniList catalogue is unavailable right now. No anime availability was inferred.</div> : anime.data?.status === "rate_limited" ? <div className="rounded-2xl border border-[#ead8ad] bg-[#fffaed] p-5 text-sm leading-6 text-[#7d6530]">Anime discovery is temporarily rate-limited. Existing legal-offer results and public-web context remain separate.</div> : anime.data?.titles?.length ? <div className="grid gap-4 sm:grid-cols-2">{anime.data.titles.map(item => <article key={item.id} className="rounded-2xl border border-[#d9d1c0] bg-[#fcfaf4] p-4 shadow-[0_4px_16px_rgba(43,66,53,.04)]"><div className="flex gap-4">{item.coverImage ? <img src={item.coverImage} alt="" loading="lazy" className="h-24 w-16 shrink-0 rounded-lg object-cover bg-[#ebe5d8]" /> : <div className="grid h-24 w-16 shrink-0 place-items-center rounded-lg bg-[#ebe5d8] text-[#61756c]"><Sparkles className="size-5" /></div>}<div className="min-w-0"><div className="flex flex-wrap gap-1.5">{item.format ? <Badge className="bg-[#e8f0e7] text-[0.62rem] text-[#3b6650]">{item.format}</Badge> : null}{item.averageScore ? <Badge className="bg-[#f3ead4] text-[0.62rem] text-[#72582d]">AniList {item.averageScore}/100</Badge> : null}</div><h3 className="serif mt-2 text-xl leading-tight text-[#294e3f]">{item.title}</h3>{item.nativeTitle && item.nativeTitle !== item.title ? <p className="mt-1 text-xs text-[#697b73]">{item.nativeTitle}</p> : null}{item.episodes ? <p className="mt-2 text-xs text-[#63766e]">{item.episodes} episodes</p> : null}</div></div>{item.genres.length ? <div className="mt-3 flex flex-wrap gap-1.5">{item.genres.slice(0, 4).map(genre => <span key={genre} className="rounded-full bg-[#f0eee7] px-2 py-1 text-[0.64rem] font-semibold text-[#61736a]">{genre}</span>)}</div> : null}{item.description ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-[#64766e]">{item.description}</p> : null}{item.siteUrl ? <a href={item.siteUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-[#436d58] underline underline-offset-2">AniList catalogue record <ExternalLink className="size-3" /></a> : null}<AnimeAvailabilityPreview title={item.title} englishTitle={item.englishTitle} nativeTitle={item.nativeTitle} region={region} language={language} /></article>)}</div> : <div className="rounded-2xl border border-dashed border-[#c9c0ae] bg-[#faf8f1]/60 p-5 text-sm leading-6 text-[#61756c]">No AniList anime matched “{query}”. Legal availability was not inferred from an empty anime-catalogue search.</div>}
  </section>;
}
