import CardCommunityContribution from "@/components/CardCommunityContribution";
import React from "react";
import CatalogOfferPreview from "@/components/CatalogOfferPreview";
import LeavingSoonSignal from "@/components/LeavingSoonSignal";
import QuickWatchlistSave from "@/components/QuickWatchlistSave";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Bot, Compass, ExternalLink, Loader2, RefreshCw, Send, Sparkles } from "lucide-react";
import { useRef, useState } from "react";

type TitleSelection = { id: number; mediaType: "movie" | "tv" };
type ConversationTurn = { prompt: string; result: any };

export default function NaturalRecommendationChat({ region, language, userSignedIn, onSelect }: { region: string; language: string; userSignedIn: boolean; onSelect: (title: TitleSelection) => void }) {
  const [prompt, setPrompt] = useState("");
  const [turns, setTurns] = useState<ConversationTurn[]>([]);
  const [lastError, setLastError] = useState<string | null>(null);
  const pendingPrompt = useRef("");
  const recommendation = trpc.ai.recommend.useMutation({
    onSuccess: result => { setTurns(previous => [...previous, { prompt: pendingPrompt.current, result }]); pendingPrompt.current = ""; setLastError(null); },
    onError: error => { setLastError(error.message); },
  });
  const suggestions = ["I want a tense science-fiction film like Inception", "Recommend a warm Hindi-language family movie", "I liked a clever crime show — what should I watch next?", "I only have 90 minutes and want something funny"];
  const latest = turns.at(-1) ?? null;
  const send = (value = prompt) => {
    const message = value.trim();
    if (message.length < 3 || recommendation.isPending) return;
    pendingPrompt.current = message;
    setPrompt("");
    setLastError(null);
    const conversationContext = turns.slice(-3).flatMap(turn => [{ role: "user" as const, content: turn.prompt }, { role: "assistant" as const, content: String(turn.result.conversation?.reply ?? "Catalog suggestions were shown.") }]);
    recommendation.mutate({ prompt: message, conversationContext, region, language });
  };
  const picks = latest?.result?.titles?.slice(0, 3) ?? [];
  const conversation = latest?.result?.conversation;

  return <section aria-labelledby="ai-recommendation-title" className="mt-8 rounded-3xl border border-[#b8d0c0] bg-[#eaf3eb] p-5 shadow-[0_10px_28px_rgba(48,86,65,.06)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow flex items-center gap-2"><Sparkles className="size-4" />Recommendation conversation</p><h2 id="ai-recommendation-title" className="serif mt-1 text-3xl text-[#214a3a]">Tell me what you feel like watching.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5a7267]">Ask naturally about a mood, a title you liked, a genre, or the time you have. Streamwise turns your request into a small, catalog-backed shortlist.</p></div><span className="rounded-full border border-[#bfd2c3] bg-white/70 px-3 py-1.5 text-xs font-semibold text-[#426755]">Natural-language picks</span></div>
    {!latest ? <div className="mt-5 flex flex-wrap gap-2">{suggestions.map(suggestion => <button key={suggestion} type="button" onClick={() => send(suggestion)} className="min-h-11 rounded-full border border-[#c3d7c7] bg-white/80 px-3 py-2 text-left text-sm font-medium text-[#315b47] transition hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{suggestion}</button>)}</div> : <div className="mt-5 rounded-2xl border border-[#c7d8c9] bg-white/75 p-4"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#618072]">You asked</p><p className="mt-1 text-sm font-semibold leading-6 text-[#315b47]">“{latest.prompt}”</p><div aria-live="polite" className="mt-4 border-l-2 border-[#70a884] pl-4"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#618072]">A good place to start</p><p className="mt-1 text-base leading-7 text-[#36594a]">{conversation?.reply}</p></div>{conversation?.rationale ? <div className="mt-4"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#618072]">Why this fits</p><p className="mt-1 text-sm leading-6 text-[#567267]">{conversation.rationale}</p></div> : null}{conversation?.usedSavedTaste ? <p className="mt-3 rounded-lg bg-[#edf5ee] px-3 py-2 text-xs leading-5 text-[#47705b]">Your saved taste preferences helped shape this shortlist. You can change them in Settings.</p> : null}</div>}
    <form className="mt-5 flex flex-col gap-3 sm:flex-row" onSubmit={event => { event.preventDefault(); send(); }}><div className="flex-1"><label className="sr-only" htmlFor="ai-recommendation-prompt">Ask for a recommendation</label><textarea id="ai-recommendation-prompt" value={prompt} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") { event.preventDefault(); send(); } }} onChange={event => setPrompt(event.target.value)} rows={3} maxLength={500} placeholder="For example: I want a funny Korean movie like…" className="min-h-20 w-full resize-none rounded-2xl border border-[#b8cfbf] bg-white px-4 py-3 text-sm text-[#274e3d] placeholder:text-[#7b8e85] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" /><p className="mt-1 text-xs text-[#698076]">Write naturally. Use ⌘/Ctrl + Enter to send.</p></div><Button type="submit" disabled={prompt.trim().length < 3 || recommendation.isPending} className="min-h-12 rounded-2xl bg-[#1e4a3a] px-5 text-white hover:bg-[#153a2d]">{recommendation.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Ask Streamwise</Button></form>
    {recommendation.isPending ? <div role="status" className="mt-5 rounded-2xl border border-[#c7d8c9] bg-white px-4 py-3 text-sm text-[#49685a]"><Loader2 className="mr-2 inline size-4 animate-spin" />Reading your request and preparing catalog-backed options…</div> : null}
    {lastError ? <div role="alert" className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#e0b9a7] bg-[#fff8f3] p-4 text-sm text-[#8a4b2c]"><span>{lastError}</span><Button type="button" size="sm" variant="outline" onClick={() => send(pendingPrompt.current)} className="border-[#bd8c79] text-[#8a4b2c]"><RefreshCw className="size-3.5" />Try again</Button></div> : null}
    {latest && picks.length ? <div className="mt-6"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow">Your shortlist</p><h3 className="serif mt-1 text-2xl text-[#244e3c]">Three picks to consider.</h3></div><Compass className="mb-1 size-5 text-[#54806a]" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{picks.map((title: any, index: number) => <article key={`${title.mediaType}-${title.id}`} className="rounded-2xl border border-[#c7d8c9] bg-white p-4"><button type="button" onClick={() => onSelect({ id: title.id, mediaType: title.mediaType })} className="w-full text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#608171]">Pick {index + 1} · {title.mediaType === "movie" ? "Film" : "Series"}{title.releaseDate ? ` · ${title.releaseDate.slice(0, 4)}` : ""}</p><h4 className="serif mt-2 text-xl text-[#244e3c]">{title.title}</h4><p className="mt-2 line-clamp-2 text-sm leading-5 text-[#64786e]">{title.overview || "Open to compare country-specific legal offers."}</p><CatalogOfferPreview titleId={title.id} mediaType={title.mediaType} region={region} language={language} /></button><LeavingSoonSignal titleId={title.id} mediaType={title.mediaType} region={region} /><div className="mt-3 flex flex-wrap gap-2"><QuickWatchlistSave titleId={title.id} mediaType={title.mediaType} title={title.title} posterPath={title.posterPath} releaseDate={title.releaseDate} region={region} language={language} /><CardCommunityContribution titleId={title.id} mediaType={title.mediaType} title={title.title} region={region} /></div></article>)}</div>{conversation?.nextStep ? <p className="mt-4 rounded-xl bg-white/65 p-3 text-sm leading-6 text-[#526f61]">{conversation.nextStep}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><span className="self-center text-sm font-semibold text-[#416653]">Keep the conversation going:</span>{picks.map((title: any) => <button key={`follow-${title.id}`} type="button" onClick={() => send(`More like ${title.title}, but with a different mood.`)} className="min-h-10 rounded-full border border-[#b6cfba] bg-white px-3 py-1.5 text-sm font-semibold text-[#315c49]">More like {title.title}</button>)}<button type="button" onClick={() => { setTurns([]); setLastError(null); }} className="min-h-10 rounded-full border border-[#b6cfba] bg-white px-3 py-1.5 text-sm font-semibold text-[#315c49]">Start a new conversation</button></div></div> : latest && !recommendation.isPending ? <p className="mt-5 rounded-xl bg-white/70 p-4 text-sm text-[#5a7267]">No catalog matches were returned. Try naming a title you liked, a mood, or a genre.</p> : null}
    {latest ? <PublicReading research={conversation?.research ?? null} userSignedIn={userSignedIn} /> : null}
  </section>;
}

function PublicReading({ research, userSignedIn }: { research: any | null; userSignedIn: boolean }) {
  if (!userSignedIn) return <p className="mt-5 rounded-xl border border-[#d8cfb8] bg-[#fffaf0] p-4 text-sm leading-6 text-[#695b3e]">Sign in to add optional source-linked public reading to this conversation. It remains separate from catalog picks and legal availability.</p>;
  if (!research) return null;
  return <aside className="mt-5 rounded-2xl border border-[#cbd8cc] bg-[#f2f6f0] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#315c49]"><Bot className="size-4" />Optional public reading</div><p className="mt-2 text-sm leading-6 text-[#466459]">{research.directResponse}</p>{research.sources?.length ? <div className="mt-3 border-t border-[#d8e2d8] pt-3"><p className="text-xs font-bold uppercase tracking-[0.08em] text-[#597366]">Critic and reporting links</p><div className="mt-2 flex flex-wrap gap-2">{research.sources.map((source: any) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="inline-flex min-h-9 items-center gap-1 rounded-full border border-[#bfd0c2] bg-white px-3 py-1.5 text-xs font-semibold text-[#2d664e] underline underline-offset-4">{source.title} <ExternalLink className="size-3" /></a>)}</div></div> : null}{research.communitySources?.length ? <div className="mt-3 rounded-xl border border-dashed border-[#decfae] bg-[#fffaf0] p-3"><p className="text-xs font-bold text-[#786033]">Public discussion — unverified</p><p className="mt-1 text-xs leading-5 text-[#796c50]">These links provide reading context only; they do not rank titles or prove legal availability.</p></div> : null}<p className="mt-3 text-xs leading-5 text-[#6d5d37]">{research.limitation}</p></aside>;
}
