import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ExternalLink, Star } from "lucide-react";

type TitleIdentity = { id: number; mediaType: "movie" | "tv"; title: string; releaseDate: string | null; imdbId?: string | null; tmdbVoteAverage?: number | null; tmdbVoteCount?: number | null };

function tmdbScore(value: number | null | undefined) { return typeof value === "number" && Number.isFinite(value) && value > 0 ? `${value.toFixed(1)} / 10` : "Not available"; }

export function TitleRatingsPanel({ title }: { title: TitleIdentity }) {
  const omdb = trpc.ratings.omdb.useQuery({ title: title.title, releaseDate: title.releaseDate, mediaType: title.mediaType, imdbId: title.imdbId ?? null }, { enabled: Boolean(title.title), retry: false, staleTime: 5 * 60_000 });
  return <section className="mt-6 rounded-2xl border border-[#d7d1c1] bg-[#fcfaf5] p-5" aria-label="Source-labelled title ratings"><p className="eyebrow">Ratings at a glance</p><p className="mt-2 text-sm leading-6 text-[#64766e]">Each source remains separate. TMDb shows its community vote metadata; OMDb returns only the matched title’s source-labelled rating values.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><article className="rounded-xl border border-[#c8d9ca] bg-[#eff6ef] p-4"><p className="mono text-[0.65rem] font-bold uppercase tracking-[0.11em] text-[#3f6a51]">TMDb community</p><p className="mt-2 flex items-center gap-1 text-2xl font-bold text-[#214a3a]"><Star className="size-5 fill-[#c3913c] text-[#c3913c]" />{tmdbScore(title.tmdbVoteAverage)}</p><p className="mt-1 text-xs text-[#597168]">{title.tmdbVoteCount ? `${title.tmdbVoteCount.toLocaleString()} TMDb votes` : "Vote count unavailable"}</p></article><article className="rounded-xl border border-[#d8d1c1] bg-white p-4"><p className="mono text-[0.65rem] font-bold uppercase tracking-[0.11em] text-[#765f32]">OMDb matched-title ratings</p>{omdb.isLoading ? <Skeleton className="mt-3 h-10 w-3/4" /> : omdb.data?.status === "available" && omdb.data.ratings.length ? <div className="mt-3 flex flex-wrap gap-2">{omdb.data.ratings.map(rating => <Badge key={rating.source} variant="outline" className="border-[#d6c49a] bg-[#fffaf0] text-[#62502b]">{rating.source}: {rating.value}</Badge>)}</div> : <p className="mt-3 text-sm leading-5 text-[#6c756e]">{omdb.data?.status === "not_configured" ? "OMDb ratings are not configured." : omdb.data?.status === "not_found" ? "No exact OMDb title match was returned." : "OMDb ratings are temporarily unavailable."}</p>}<p className="mt-3 text-xs leading-5 text-[#756b57]">IMDb, Rotten Tomatoes, and Metacritic values appear only when OMDb returns them for this matched title.</p></article></div></section>;
}

export function TmdbReviewPanel({ title }: { title: Pick<TitleIdentity, "id" | "mediaType"> }) {
  const reviews = trpc.catalog.reviews.useQuery({ id: title.id, mediaType: title.mediaType }, { retry: false, staleTime: 5 * 60_000 });
  if (reviews.isLoading) return <section className="mt-6 rounded-2xl border border-[#d8d0c0] bg-[#fcfaf4] p-5"><p className="eyebrow">TMDb user reviews</p><Skeleton className="mt-4 h-20 w-full" /></section>;
  if (!reviews.data?.configured || !reviews.data.reviews.length) return <section className="mt-6 rounded-2xl border border-[#d8d0c0] bg-[#fcfaf4] p-5"><p className="eyebrow">TMDb user reviews</p><p className="mt-2 text-sm leading-6 text-[#64766e]">{reviews.data?.configured ? "TMDb returned no user-review excerpts for this title right now." : "TMDb review context is unavailable until the catalog provider is configured."}</p></section>;
  return <section className="mt-6 rounded-2xl border border-[#d8d0c0] bg-[#fcfaf4] p-5"><p className="eyebrow">TMDb user reviews</p><p className="mt-2 text-sm leading-6 text-[#64766e]">These are source-labelled TMDb user-review excerpts, separate from Streamwise member reviews and editorial reading links.</p><div className="mt-4 space-y-3">{reviews.data.reviews.map((review, index) => <article key={`${review.author}-${review.createdAt ?? index}`} className="rounded-xl border border-[#e1dbce] bg-white/70 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-[#315c49]">TMDb member: {review.author}</p>{review.rating ? <Badge className="bg-[#edf4ec] text-[#315c49]">TMDb rating: {review.rating}/10</Badge> : null}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#596e65]">{review.content}</p>{review.url ? <a href={review.url} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-[#315c49] underline underline-offset-2">Read on TMDb <ExternalLink className="size-3" /></a> : null}</article>)}</div></section>;
}
