import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { BookOpen, ExternalLink } from "lucide-react";

const articleImage = "/manus-storage/streamwise-original-article_f2b5cfdc.webp";

export function WhyStreamwiseButton({ onClick }: { onClick: () => void }) {
  return <Button onClick={onClick} variant="outline" size="sm" className="border-[#d5c7ae] bg-white/70 text-[#315c4b] hover:bg-[#fffaf0]"><BookOpen className="size-3.5" />Why Streamwise exists</Button>;
}

export default function WhyStreamwiseDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto border-[#d9d3c4] bg-[#fcfaf4] sm:max-w-4xl"><DialogHeader><p className="eyebrow">The original consumer problem</p><DialogTitle className="serif text-3xl text-[#214a3a]">Finding a film should not require managing a maze.</DialogTitle><DialogDescription className="max-w-2xl leading-6">This user-provided article documents the friction Streamwise was built to reduce: hunting across platforms, uncertainty about catalog changes, subscription sprawl, and the fear of cancelling the wrong service.</DialogDescription></DialogHeader><div className="mt-3 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl border border-[#d8d0c0] bg-[#fffdf7] p-4"><img src={articleImage} alt="User-provided newspaper article about streaming discovery and subscription frustration" className="w-full rounded-lg border border-[#d8d0c0]" loading="lazy" /><a href={articleImage} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#2f634f] underline underline-offset-4">Open article image <ExternalLink className="size-3" /></a></div><div className="space-y-3"><p className="text-sm leading-6 text-[#5a7066]">The article’s everyday challenge is not simply choosing entertainment. It is making a legal, timely choice when titles move, offerings differ by service and region, pricing is scattered, and an unused subscription can feel risky to cancel.</p><div className="rounded-xl bg-[#eaf1e9] p-4 text-sm leading-6 text-[#49695b]"><strong className="text-[#2d5c48]">How Streamwise responds:</strong> one country-aware legal catalog; snapshots and opt-in change checks; watchlist intent; transparent keep, pause, and cancel candidates; clear provider/cancellation guidance; and public discussion visibly separated from verified evidence.</div><div className="rounded-xl bg-[#f4ead7] p-4 text-sm leading-6 text-[#6a5c3e]"><strong className="text-[#664d24]">What it does not promise:</strong> catalog permanence, price eligibility, a predicted leaving date, or automatic cancellations. Always confirm the final offer with the provider.</div></div></div></DialogContent></Dialog>;
}
